In [56]:
import requests
import json
import pandas as pd

In [57]:
url = "https://api-baseball.p.rapidapi.com/standings"

querystring = {"league":"1","season":"2020"}

headers = {
	"X-RapidAPI-Key": "55194652f4msh40bd2e5941627eap1b1b68jsn4f55d7d0851b",
	"X-RapidAPI-Host": "api-baseball.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

In [58]:
if response.status_code == 200:
  data = response.json()

  formatted_json = json.dumps(data, sort_keys=True, indent = 10)
  #print(formatted_json)

team_names = []
games_played = []
wins = []
lose = []
points_for = []
points_against = []


for team in data['response'][0]:
  team_names.append(team['team']['name'])
  games_played.append(team['games']['played'])
  wins.append(team['games']['win']['total'])
  lose.append(team['games']['lose']['total'])
  points_for.append(team['points']['for'])
  points_against.append(team['points']['against'])

  teams_data = {
    'Team Names':team_names,
    'Games Played':games_played,
    'Wins': wins,
    'Lose': lose,
    'For': points_for,
    'Against':points_against
}

df = pd.DataFrame(teams_data)
df

               Team Names  Games Played  Wins  Lose  For  Against
0          Tampa Bay Rays            60    40    20  289      229
1         Minnesota Twins            60    36    24  269      215
2       Oakland Athletics            60    36    24  274      232
3       Chicago White Sox            60    35    25  306      246
4       Cleveland Indians            60    35    25  248      209
5        New York Yankees            60    33    27  315      270
6       Toronto Blue Jays            60    32    28  302      312
7          Houston Astros            60    29    31  279      275
8        Seattle Mariners            60    27    33  254      303
9      Los Angeles Angels            60    26    34  294      321
10     Kansas City Royals            60    26    34  248      272
11      Baltimore Orioles            60    25    35  274      294
12         Boston Red Sox            60    24    36  292      351
13         Detroit Tigers            58    23    35  249      318
14          Texas Rangers            60    22    38  224      312
15    Los Angeles Dodgers            60    43    17  349      213
16       San Diego Padres            60    37    23  325      241
17         Atlanta Braves            60    35    25  348      288
18           Chicago Cubs            60    34    26  265      240
19          Miami Marlins            60    31    29  263      304
20        Cincinnati Reds            60    31    29  243      243
21     St.Louis Cardinals            58    30    28  240      229
22      Milwaukee Brewers            60    29    31  247      264
23   San Francisco Giants            60    29    31  299      297
24  Philadelphia Phillies            60    28    32  306      311
25   Washington Nationals            60    26    34  293      301
26       Colorado Rockies            60    26    34  275      353
27          New York Mets            60    26    34  286      308
28   Arizona Diamondbacks            60    25    35  269      295
29     Pittsburgh Pirates            60    19    41  219      298
30         Tampa Bay Rays            60    40    20  289      229
31       New York Yankees            60    33    27  315      270
32      Toronto Blue Jays            60    32    28  302      312
33      Baltimore Orioles            60    25    35  274      294
34         Boston Red Sox            60    24    36  292      351
35        Minnesota Twins            60    36    24  269      215
36      Chicago White Sox            60    35    25  306      246
37      Cleveland Indians            60    35    25  248      209
38     Kansas City Royals            60    26    34  248      272
39         Detroit Tigers            58    23    35  249      318
40      Oakland Athletics            60    36    24  274      232
41         Houston Astros            60    29    31  279      275
42       Seattle Mariners            60    27    33  254      303
43     Los Angeles Angels            60    26    34  294      321
44          Texas Rangers            60    22    38  224      312
45         Atlanta Braves            60    35    25  348      288
46          Miami Marlins            60    31    29  263      304
47  Philadelphia Phillies            60    28    32  306      311
48   Washington Nationals            60    26    34  293      301
49          New York Mets            60    26    34  286      308
50           Chicago Cubs            60    34    26  265      240
51        Cincinnati Reds            60    31    29  243      243
52     St.Louis Cardinals            58    30    28  240      229
53      Milwaukee Brewers            60    29    31  247      264
54     Pittsburgh Pirates            60    19    41  219      298
55    Los Angeles Dodgers            60    43    17  349      213
56       San Diego Padres            60    37    23  325      241
57   San Francisco Giants            60    29    31  299      297
58       Colorado Rockies            60    26    34  275      353
59   Arizona Diamondbacks            60    25    35  269      295

In [60]:
df.describe().round(1)

       Games Played  Wins  Lose    For  Against
count          60.0  60.0  60.0   60.0     60.0
mean           59.9  29.9  29.9  278.1    278.1
std             0.5   5.6   5.5   32.3     40.0
min            58.0  19.0  17.0  219.0    209.0
25%            60.0  26.0  25.0  249.0    241.0
50%            60.0  29.0  31.0  274.5    291.0
75%            60.0  35.0  34.0  299.0    308.0
max            60.0  43.0  41.0  349.0    353.0

In [61]:
df.to_csv('baseball_standings.csv', index=False)